fix not enabled in tampermonkey for Chrome and Safari, and add a link to youdao
intellilab/translator.user.js pull request #7
Opened 2018-01-28 02:55 UTC by sunjie21

2018-01-30 07:57 UTC, gera2ld requested changes

2018-01-30 07:57 UTC, gera2ld commented on src/index.js
> +    header.appendChild(createElement('a', { textContent: '详情' }, { target: '_blank', href: `http://dict.youdao.com/search?q=${query}` }));
不如把上面两个span也都用a标签吧，query是不是应该encodeURIComponent一下

2018-01-30 07:57 UTC, gera2ld commented on src/style.css
> +  > [data-type], a {
这里统一给a标签加样式好了

2018-02-04 10:11 UTC, sunjie21 commented on src/style.css
> +  > [data-type], a {
已经修改了

2018-02-05 03:35 UTC, merged